_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.9
            "8":
                - 5
                - 9
            "12": 0.19.9
            "13": linux-x86_64
